const ITEMS = [{"seq": 1, "location": "Chicken Cooler", "ref": 19551, "name": "Chicken", "packSize": "8 Bags", "pack": 8}, 
    {"seq": 2, "location": "Chicken Cooler", "ref": 25259, "name": "Chicken Wings", "packSize": "1 Bag", "pack": 1}, 
    {"seq": 3, "location": "Chicken Cooler", "ref": 1470, "name": "Breast", "packSize": "80/Case", "pack": 80}, 
    {"seq": 4, "location": "Chicken Cooler", "ref": 25138, "name": "Legs", "packSize": "125/Case", "pack": 125}, 
    {"seq": 5, "location": "Stockroom", "ref": 13005, "name": "Shortening Fry", "packSize": "1 Cont.", "pack": 1}, 
    {"seq": 6, "location": "Stockroom", "ref": 13006, "name": "Shortening Cube", "packSize": "1 Box", "pack": 1}, 
    {"seq": 7, "location": "Stockroom", "ref": 10200, "name": "Flour Breading", "packSize": "1 Bag", "pack": 1}, 
    {"seq": 9, "location": "Stockroom", "ref": 17006, "name": "Royal Mild", "packSize": "40 Packs", "pack": 40}, 
    {"seq": 10, "location": "Freezer", "ref": 101883, "name": "Supremes", "packSize": "8 Bags", "pack": 8}, 
    {"seq": 12, "location": "Cooler", "ref": 10215, "name": "Premade Dries", "packSize": "6 Bags", "pack": 6}, 
    {"seq": 14, "location": "Cooler", "ref": 14004, "name": "Cheddar Cheese", "packSize": "6 Packs", "pack": 6}, 
    {"seq": 15, "location": "Freezer", "ref": 14401, "name": "Fries", "packSize": "6 Bags", "pack": 6}, 
    {"seq": 16, "location": "Freezer", "ref": 101869, "name": "Bo Rounds", "packSize": "6 Bags", "pack": 6}, 
    {"seq": 20, "location": "Stockroom", "ref": 17352, "name": "Pintos", "packSize": "6 Cans", "pack": 6}, 
    {"seq": 21, "location": "Freezer", "ref": 101872, "name": "Mac and Cheese", "packSize": "8 Bags", "pack": 8}, 
    {"seq": 23, "location": "Stockroom", "ref": 17323, "name": "Rice", "packSize": "1 Bag", "pack": 1}, 
    {"seq": 27, "location": "Stockroom", "ref": 17030, "name": "Fry Seasoning", "packSize": "25 Bags", "pack": 25}, 
    {"seq": 28, "location": "Stockroom", "ref": 17004, "name": "Pintos Seasoning", "packSize": "120 Pcks", "pack": 120}, 
    {"seq": 29, "location": "Stockroom", "ref": 17026, "name": "Dirty Rice Seasoning", "packSize": "100 Packs", "pack": 100}, 
    {"seq": 30, "location": "Cooler", "ref": 14000, "name": "American Cheese", "packSize": "8 Sleeves", "pack": 8}, 
    {"seq": 31, "location": "Freezer", "ref": 16002, "name": "Steak", "packSize": "6 Boxes", "pack": 6}, 
    {"seq": 32, "location": "Breakfast Meats", "ref": 102167, "name": "Smoked Sausage", "packSize": "2 Bags", "pack": 2}, 
    {"seq": 34, "location": "Breakfast Meats", "ref": 16502, "name": "Ham", "packSize": "3 Bags", "pack": 3}, 
    {"seq": 35, "location": "Breakfast Meats", "ref": 102252, "name": "Bacon", "packSize": "4 Bags", "pack": 4}, 
    {"seq": 36, "location": "Breakfast Meats", "ref": 16523, "name": "Sausage", "packSize": "2 Boxes", "pack": 2}, 
    {"seq": 37, "location": "Cooler", "ref": 14201, "name": "Eggs", "packSize": "15 Cartons", "pack": 15}, 
    {"seq": 38, "location": "Cooler", "ref": 14011, "name": "Whipped Margarine", "packSize": "1 Tub", "pack": 1}, 
    {"seq": 42, "location": "Stockroom", "ref": 17020, "name": "Biscuit Magic", "packSize": "96 Packs", "pack": 96}, 
    {"seq": 43, "location": "Cooler", "ref": 14001, "name": "Buttermilk", "packSize": "9 Jugs", "pack": 9}, 
    {"seq": 48, "location": "Cooler", "ref": 15502, "name": "Orange Juice", "packSize": "24/Case", "pack": 24}, 
    {"seq": 50, "location": "Drinks", "ref": 15001, "name": "Diet Pepsi", "packSize": "1 Bag in Box", "pack": 1}, 
    {"seq": 51, "location": "Drinks", "ref": 15005, "name": "Diet Mountain Dew", "packSize": "1 Bag in Box", "pack": 1}, 
    {"seq": 55, "location": "Drinks", "ref": 15002, "name": "Mountain Dew", "packSize": "1 Bag in Box", "pack": 1}, 
    {"seq": 56, "location": "Drinks", "ref": 15000, "name": "Pepsi", "packSize": "1 Bag in Box", "pack": 1}, 
    {"seq": 60, "location": "Drinks", "ref": 15603, "name": "Tea Bags", "packSize": "110 Packs", "pack": 110}, 
    {"seq": 62, "location": "Drinks", "ref": 15205, "name": "Coffee", "packSize": "176 Packs", "pack": 176}, 
    {"seq": 69, "location": "Drinks", "ref": 15010, "name": "Lemonade", "packSize": "1 Bag in Box", "pack": 1}, 
    {"seq": 70, "location": "Drinks", "ref": 15605, "name": "Dr. Pepper", "packSize": "1 Bag in Box", "pack": 1}, 
    {"seq": 73, "location": "Stockroom", "ref": 15604, "name": "Sugar Granulate", "packSize": "10 Bags", "pack": 10}, 
    {"seq": 90, "location": "Chicken Cooler", "ref": 101919, "name": "Bo Bites", "packSize": "8 Bags", "pack": 8}, 
    {"seq": 95, "location": "Freezer", "ref": 101885, "name": "Filets", "packSize": "6 Bags", "pack": 6}, 
    {"seq": 96, "location": "Freezer", "ref": 16229, "name": "Grills", "packSize": "8 Bags", "pack": 8}, 
    {"seq": 97, "location": "Breakfast Meats", "ref": 26301, "name": "Bologna", "packSize": "30 Bags", "pack": 30},
    {"seq": 180, "location": "Freezer", "ref": 101744, "name": "Fish", "packSize": "1 Bag", "pack": 1},
    {"seq": 182, "location": "Chicken Cooler", "ref": 97677, "name": "Thigh/Leg", "packSize": "1 Bag", "pack": 1}, 
    {"seq": 201, "location": "Cooler", "ref": 14003, "name": "Shredded Cheese", "packSize": "4 Bags", "pack": 4}, 
    {"seq": 213, "location": "Freezer", "ref": 16513, "name": "Pork Chop", "packSize": "4 Boxes", "pack": 4}, 
    {"seq": 216, "location": "Cooler", "ref": 101867, "name": "Salad Mix", "packSize": "4 Bags", "pack": 4}, 
    {"seq": 219, "location": "Cooler", "ref": 102166, "name": "Shredded Lettuce", "packSize": "4 Bags", "pack": 4}, 
    {"seq": 224, "location": "Cooler", "ref": 17359, "name": "Pimento Cheese", "packSize": "4 Tubs", "pack": 4}, 
    {"seq": 305, "location": "Drinks", "ref": 101874, "name": "Starry", "packSize": "1 Bag in Box", "pack": 1}, 
    {"seq": 306, "location": "Drinks", "ref": 15023, "name": "Pepsi Zero", "packSize": "1 Bag in Box", "pack": 1}, 
    {"seq": 308, "location": "Drinks", "ref": 15602, "name": "Cheerwine", "packSize": "1 Bag in Box", "pack": 1}, 
    {"seq": 309, "location": "Drinks", "ref": 101786, "name": "Cold Brew", "packSize": "6 Bottles", "pack": 6}, 
    {"seq": 310, "location": "Drinks", "ref": 102294, "name": "Sweet Cream Vanilla", "packSize": "6 Cartons", "pack": 6}, 
    {"seq": 311, "location": "Drinks", "ref": 101809, "name": "Vanilla Syrup", "packSize": "12 Bottles", "pack": 12}, 
    {"seq": 312, "location": "Drinks", "ref": 102273, "name": "Caramel Sauce", "packSize": "4 Bottles", "pack": 4}, 
    {"seq": 314, "location": "Freezer", "ref": 101905, "name": "Bun Bird Dog", "packSize": "12 Bags", "pack": 12}, 
    {"seq": 329, "location": "Stockroom", "ref": 18356, "name": "Dura Fry", "packSize": "1 Bag", "pack": 1}, 
    {"seq": 330, "location": "Freezer", "ref": 102168, "name": "Buns", "packSize": "3 Boxes/15 Bags", "pack": 15}, 
    {"seq": 331, "location": "Stockroom", "ref": 101866, "name": "Bo Batter", "packSize": "10 Bags", "pack": 10}, 
    {"seq": 332, "location": "Stockroom", "ref": 101848, "name": "Bo Breading", "packSize": "1 Bag", "pack": 1}, 
    {"seq": 334, "location": "Chicken Cooler", "ref": 101914, "name": "Bo Chicken", "packSize": "8 Bags", "pack": 8}];
